### ISSUE TITLE
EtherPad crashes every 10 minutes

### ISSUE THREAD

**Issue by BlackyFox** [aoberegg/ep_user_pad_frontend#13]
Hi ! 
I was testing some stuff and plugins on EtherPad (ep_user_pad & ep_user_pad_frontend) and I noticed that EtherPad was crashing a lot of time. At first I tought it was an issue due to mysql utf8 (and not utf8mb4) but it is still crashing after changing the charset as explain in issue #2522.
So, here is my log, and I have no idea what can cause that kind of shutdown...
```bash
[2015-07-06 16:30:57.346] [INFO] ueberDB - Flushed 1 values
[2015-07-06 16:31:01.231] [ERROR] console - Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/antoine/Bureau/test_ep_etherpad/etherpad-lite/node_modules/ep_user_pad/node_modules/mysql/lib/protocol/Protocol.js:73:13)
    at Socket.onend (_stream_readable.js:505:10)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
[2015-07-06 16:31:01.231] [INFO] console - graceful shutdown...
[2015-07-06 16:31:01.233] [ERROR] console - Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/antoine/Bureau/test_ep_etherpad/etherpad-lite/node_modules/ep_user_pad/node_modules/mysql/lib/protocol/Protocol.js:73:13)
    at Socket.onend (_stream_readable.js:505:10)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
[2015-07-06 16:31:01.305] [INFO] console - db sucessfully closed.
```

**Comment by BlackyFox** [comment]
Hi again ! 
I was checking the dependencies thos two plugins have, and I saw they need the mysql package, version 2.0.0-alpha9.
I tried using the version 2.6.1 (wich have the ping on idle implemented) but it cannot connect to the database then.
Maybe there is something to change I couldn't find in the code that can't make it work with 2.6.1. 
Can anyone check on this ?

Thanks !
