### ISSUE TITLE
Crashes every time user click on activation link from email.

### ISSUE THREAD

**Issue by aedahh** [aoberegg/ep_user_pad_frontend#9]
Hello, 

My setup:
-Ubuntu
-Etherpad version from git: a676640
node js v0.10.37

Etherpad crashes with log below.
Happens every time user click on activation link from email.

[2015-03-25 17:56:50.832] [INFO] ueberDB - Flushed 3 values
[2015-03-25 17:57:04.240] [ERROR] console - ReferenceError: fileName is not defined
    at Query.mySqlErrorHandler (/opt/etherpad/local/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/hooks.js:42:9)
    at Query.emit (events.js:117:20)
    at Query.Sequence.end (/opt/etherpad/local/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/protocol/sequences/Sequence.js:70:12)
    at Query.ErrorPacket (/opt/etherpad/local/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
    at Protocol._parsePacket (/opt/etherpad/local/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/protocol/Protocol.js:172:24)
    at Parser.write (/opt/etherpad/local/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/opt/etherpad/local/etherpad/etherpad-lite/node_modules/ep_user_pad_frontend/node_modules/mysql/lib/protocol/Protocol.js:37:16)
    at Socket.ondata (stream.js:51:26)
    at Socket.emit (events.js:117:20)
    at Socket.<anonymous> (_stream_readable.js:765:14)
[2015-03-25 17:57:04.240] [INFO] console - graceful shutdown...

**Comment by PabloCastellano** [comment]
Had this same problem testing in a Debian Jessie virtual machine but not in a Ubuntu Xenial virtual machine. Both had nodejs installed from the nodejs repositories (instead of Debian/Ubuntu official repos).
